### ISSUE TITLE
2.9.11 launch checklist

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1787]
Just a general checklist, since we made some changes that require attention before launching.

- [ ] Minify `admin-styles.css`
- [ ] Minify `forms.css`
- [ ] Minify `register.js`
- [ ] Add admin notice for Stripe Connect
- [ ] Update .pot file
- [ ] Bump version numbers
